version: "3.8"

services:
  mongo:
    container_name: mongo
    image: mongo:7.0
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./.docker-volumes/mongo/data:/data/db
      # - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - '27017:27017'
    # expose:
    #   - 27017